development:
  adapter: postgresql
  host: localhost
  database: kjdb_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: kjdb_development
  pool: 5
  timeout: 5000
